compute_environment: LOCAL_MACHINE
debug: false
downcast_bf16: 'no'
distributed_type: MULTI_GPU
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false